import { MigrationInterface, QueryRunner } from "typeorm";

export class AddInfluencerDiscoveryFields1772619137864 implements MigrationInterface {
    name = 'AddInfluencerDiscoveryFields1772619137864'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "fk_brands_user"`);
        await queryRunner.query(`ALTER TABLE "social_metrics" DROP CONSTRAINT "FK_social_metrics_account"`);
        await queryRunner.query(`ALTER TABLE "social_audience_insights" DROP CONSTRAINT "FK_social_insights_account"`);
        await queryRunner.query(`ALTER TABLE "social_accounts" DROP CONSTRAINT "FK_social_accounts_influencer"`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP CONSTRAINT "fk_influencers_user"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be"`);
        await queryRunner.query(`ALTER TABLE "tracking_links" DROP CONSTRAINT "FK_472c744e97dbcc4bab5ca63af01"`);
        await queryRunner.query(`ALTER TABLE "tracking_links" DROP CONSTRAINT "FK_b3409d200515fd2deece569a82f"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_35ca8b0cc9cd29f1ec4c404eb95"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_2b3de6b04e1a38f83e1e85c14be"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_ad3c2a862c329d544f652f7b83c"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_f26c816a183ac87bcca7810a464"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP CONSTRAINT "FK_b73adffd7ba59a8352387739b84"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP CONSTRAINT "FK_1bfb3f36a926c9160ba5f96f249"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_brand"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_influencer"`);
        await queryRunner.query(`ALTER TABLE "brand_integrations" DROP CONSTRAINT "FK_brand_integrations_brand"`);
        await queryRunner.query(`DROP INDEX "public"."idx_brands_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_brands_api_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_metrics_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_metrics_synced"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_insights_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_insights_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_accounts_verified"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_accounts_influencer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_social_accounts_platform"`);
        await queryRunner.query(`DROP INDEX "public"."idx_influencers_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_influencers_niche"`);
        await queryRunner.query(`DROP INDEX "public"."idx_influencers_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_oauth"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_brand_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_review_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tracking_link_products_link"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tracking_link_products_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tracking_links_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tracking_links_influencer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tracking_links_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tracking_links_custom_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tracking_links_bio_links"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_tracking_link"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_influencer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_brand"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clicks_tracking_link"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clicks_clicked_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clicks_ip"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_clicks_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_influencer_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_influencer_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_brand_influencer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaigns_brand_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaigns_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaigns_start_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaigns_end_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaigns_campaign_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaign_invitations_campaign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaign_invitations_influencer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaign_invitations_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaign_invitations_pending"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "brands_integration_type_check"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "brands_status_check"`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP CONSTRAINT "influencers_status_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_status_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "social_accounts" DROP CONSTRAINT "UQ_social_accounts_platform_user"`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" DROP CONSTRAINT "UQ_tracking_link_products_link_product"`);
        await queryRunner.query(`ALTER TABLE "tracking_links" DROP CONSTRAINT "UQ_tracking_links_influencer_product"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "UQ_conversions_brand_order"`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" DROP CONSTRAINT "UQ_campaign_invitations_campaign_influencer"`);
        await queryRunner.query(`COMMENT ON TABLE "tracking_link_products" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "campaign_invitations" IS NULL`);

        // Update null company_name values before making it NOT NULL
        await queryRunner.query(`UPDATE "brands" SET "company_name" = 'Unknown Brand' WHERE "company_name" IS NULL`);

        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "company_name" character varying NOT NULL DEFAULT 'Unknown Brand'`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "display_name" character varying`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "website" character varying`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "logo_url" character varying`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "default_commission_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "default_commission_rate" SET DEFAULT '0.1'`);

        // Update null api_key values before making it NOT NULL
        await queryRunner.query(`UPDATE "brands" SET "api_key" = uuid_generate_v4() WHERE "api_key" IS NULL`);

        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "brands_api_key_key"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "api_key"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "api_key" character varying NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "UQ_86d76ffb685a202049e6e43d5f0" UNIQUE ("api_key")`);

        // Update null pixel_id values before making it NOT NULL
        await queryRunner.query(`UPDATE "brands" SET "pixel_id" = uuid_generate_v4() WHERE "pixel_id" IS NULL`);

        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "brands_pixel_id_key"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "pixel_id"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "pixel_id" character varying NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "UQ_2a36492bc579b1fe3895f806b90" UNIQUE ("pixel_id")`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "integration_type"`);
        await queryRunner.query(`CREATE TYPE "public"."brands_integration_type_enum" AS ENUM('PIXEL', 'WEBHOOK', 'API')`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "integration_type" "public"."brands_integration_type_enum" NOT NULL DEFAULT 'PIXEL'`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."brands_status_enum" AS ENUM('ACTIVE', 'PAUSED', 'SUSPENDED')`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "status" "public"."brands_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "updated_at" SET DEFAULT now()`);

        // Update null display_name values before making it NOT NULL
        await queryRunner.query(`UPDATE "influencers" SET "display_name" = 'Unknown Influencer' WHERE "display_name" IS NULL`);

        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "display_name" character varying NOT NULL DEFAULT 'Unknown Influencer'`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "avatar_url" character varying`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_instagram"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_instagram" character varying`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_tiktok"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_tiktok" character varying`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_youtube"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_youtube" character varying`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_twitter"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_twitter" character varying`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "follower_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "niche"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "niche" character varying array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "rating" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "rating" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_sales" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_sales" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_earnings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_earnings" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_clicks" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_conversions" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."influencers_status_enum" AS ENUM('ACTIVE', 'PAUSED', 'SUSPENDED')`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "status" "public"."influencers_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "updated_at" SET DEFAULT now()`);

        // Update null email values before making it NOT NULL
        await queryRunner.query(`UPDATE "users" SET "email" = 'unknown-' || uuid_generate_v4() || '@example.com' WHERE "email" IS NULL`);

        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL DEFAULT ('unknown-' || uuid_generate_v4() || '@example.com')`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);

        // Update null password_hash values before making it NOT NULL
        await queryRunner.query(`UPDATE "users" SET "password_hash" = 'temp_hash_' || uuid_generate_v4() WHERE "password_hash" IS NULL`);

        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL DEFAULT ('temp_hash_' || uuid_generate_v4())`);

        // Update null role values before making it NOT NULL
        await queryRunner.query(`UPDATE "users" SET "role" = 'INFLUENCER' WHERE "role" IS NULL`);

        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('BRAND', 'INFLUENCER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'INFLUENCER'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'DELETED')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "oauth_provider"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "oauth_provider" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "oauth_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "oauth_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);

        // Update null product name values before making it NOT NULL
        await queryRunner.query(`UPDATE "products" SET "name" = 'Unknown Product' WHERE "name" IS NULL`);

        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "name" character varying NOT NULL DEFAULT 'Unknown Product'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image_urls"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image_urls" character varying array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category" character varying`);

        // Update null product_url values before making it NOT NULL
        await queryRunner.query(`UPDATE "products" SET "product_url" = 'https://example.com/product/' || id WHERE "product_url" IS NULL`);

        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "product_url"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "product_url" character varying NOT NULL DEFAULT 'https://example.com/product/unknown'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" SET DEFAULT 'INACTIVE'`);
        await queryRunner.query(`ALTER TYPE "public"."product_review_status_enum" RENAME TO "product_review_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."products_review_status_enum" AS ENUM('PENDING_REVIEW', 'APPROVED', 'NEEDS_REVISION', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "review_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "review_status" TYPE "public"."products_review_status_enum" USING "review_status"::"text"::"public"."products_review_status_enum"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "review_status" SET DEFAULT 'PENDING_REVIEW'`);
        await queryRunner.query(`DROP TYPE "public"."product_review_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_link_products"."display_order" IS NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."product_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."custom_slug" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."is_bio_link" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."qr_code_url" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."landing_page_config" IS NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ALTER COLUMN "updated_at" SET DEFAULT now()`);

        // Update null order_id values before making it NOT NULL
        await queryRunner.query(`UPDATE "conversions" SET "order_id" = 'ORDER-' || uuid_generate_v4() WHERE "order_id" IS NULL`);

        await queryRunner.query(`ALTER TABLE "conversions" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD "order_id" character varying NOT NULL DEFAULT ('ORDER-' || uuid_generate_v4())`);
        await queryRunner.query(`ALTER TABLE "conversions" ALTER COLUMN "converted_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "clicks"."product_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "clicks" ALTER COLUMN "clicked_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_enum" RENAME TO "notification_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('MESSAGE', 'CAMPAIGN_INVITE', 'CAMPAIGN_ACCEPTED', 'CAMPAIGN_DECLINED', 'NEW_CONVERSION', 'PAYOUT_REQUESTED', 'PAYOUT_APPROVED', 'PAYOUT_PAID', 'PRODUCT_APPROVED', 'PRODUCT_REJECTED')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum" USING "type"::"text"::"public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "campaigns"."campaign_type" IS NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "campaign_invitations"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ALTER COLUMN "invited_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brand_integrations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "brand_integrations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" ADD CONSTRAINT "UQ_31075fc89025984bbd536295d0b" UNIQUE ("tracking_link_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ADD CONSTRAINT "UQ_958e1b1365f4bf73440643d4990" UNIQUE ("influencer_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "UQ_77d76563e73f6678ab382fbb4ef" UNIQUE ("brand_id", "order_id")`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ADD CONSTRAINT "UQ_35f9c986bc4b4e9f52eafa4080e" UNIQUE ("campaign_id", "influencer_id")`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "FK_5d26f3a7d19d380538c9dd57d06" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_metrics" ADD CONSTRAINT "FK_87a7dd51bafb2988ea85560565b" FOREIGN KEY ("social_account_id") REFERENCES "social_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_audience_insights" ADD CONSTRAINT "FK_6aac10c7cac87ade608476266ec" FOREIGN KEY ("social_account_id") REFERENCES "social_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_accounts" ADD CONSTRAINT "FK_bee331541866292920baf1fdb57" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD CONSTRAINT "FK_08bb7678deabfeec3acb7e4ab88" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ADD CONSTRAINT "FK_472c744e97dbcc4bab5ca63af01" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ADD CONSTRAINT "FK_b3409d200515fd2deece569a82f" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_35ca8b0cc9cd29f1ec4c404eb95" FOREIGN KEY ("tracking_link_id") REFERENCES "tracking_links"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_2b3de6b04e1a38f83e1e85c14be" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_ad3c2a862c329d544f652f7b83c" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_f26c816a183ac87bcca7810a464" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD CONSTRAINT "FK_b73adffd7ba59a8352387739b84" FOREIGN KEY ("tracking_link_id") REFERENCES "tracking_links"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD CONSTRAINT "FK_1bfb3f36a926c9160ba5f96f249" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_eb0a4a0743bc71dd06557a1afb9" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_eb3c1e45053c2030aa599386a49" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brand_integrations" ADD CONSTRAINT "FK_6ba0c6ef0d5895769c9076bc7d0" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "brand_integrations" DROP CONSTRAINT "FK_6ba0c6ef0d5895769c9076bc7d0"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_eb3c1e45053c2030aa599386a49"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_eb0a4a0743bc71dd06557a1afb9"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP CONSTRAINT "FK_1bfb3f36a926c9160ba5f96f249"`);
        await queryRunner.query(`ALTER TABLE "clicks" DROP CONSTRAINT "FK_b73adffd7ba59a8352387739b84"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_f26c816a183ac87bcca7810a464"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_ad3c2a862c329d544f652f7b83c"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_2b3de6b04e1a38f83e1e85c14be"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_35ca8b0cc9cd29f1ec4c404eb95"`);
        await queryRunner.query(`ALTER TABLE "tracking_links" DROP CONSTRAINT "FK_b3409d200515fd2deece569a82f"`);
        await queryRunner.query(`ALTER TABLE "tracking_links" DROP CONSTRAINT "FK_472c744e97dbcc4bab5ca63af01"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be"`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP CONSTRAINT "FK_08bb7678deabfeec3acb7e4ab88"`);
        await queryRunner.query(`ALTER TABLE "social_accounts" DROP CONSTRAINT "FK_bee331541866292920baf1fdb57"`);
        await queryRunner.query(`ALTER TABLE "social_audience_insights" DROP CONSTRAINT "FK_6aac10c7cac87ade608476266ec"`);
        await queryRunner.query(`ALTER TABLE "social_metrics" DROP CONSTRAINT "FK_87a7dd51bafb2988ea85560565b"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "FK_5d26f3a7d19d380538c9dd57d06"`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" DROP CONSTRAINT "UQ_35f9c986bc4b4e9f52eafa4080e"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "UQ_77d76563e73f6678ab382fbb4ef"`);
        await queryRunner.query(`ALTER TABLE "tracking_links" DROP CONSTRAINT "UQ_958e1b1365f4bf73440643d4990"`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" DROP CONSTRAINT "UQ_31075fc89025984bbd536295d0b"`);
        await queryRunner.query(`ALTER TABLE "brand_integrations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "brand_integrations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ALTER COLUMN "invited_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "campaign_invitations"."status" IS 'PENDING = waiting for response, ACCEPTED = can create links, DECLINED = rejected invitation'`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "campaigns"."campaign_type" IS 'OPEN = visible to all influencers, SPECIFIC = invitation only'`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum_old" AS ENUM('MESSAGE', 'CAMPAIGN_INVITE', 'CAMPAIGN_ACCEPTED', 'CAMPAIGN_DECLINED', 'NEW_CONVERSION', 'PAYOUT_REQUESTED', 'PAYOUT_APPROVED', 'PAYOUT_PAID', 'PRODUCT_APPROVED', 'PRODUCT_REJECTED')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notification_type_enum_old" USING "type"::"text"::"public"."notification_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_enum_old" RENAME TO "notification_type_enum"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clicks" ALTER COLUMN "clicked_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "clicks"."product_id" IS 'For multi-product links, tracks which specific product was clicked'`);
        await queryRunner.query(`ALTER TABLE "conversions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conversions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conversions" ALTER COLUMN "converted_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP COLUMN "order_id"`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD "order_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."landing_page_config" IS 'JSON config for landing page appearance (title, description, theme)'`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."qr_code_url" IS 'Base64 data URL or Cloudinary URL of generated QR code'`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."is_bio_link" IS 'Whether this link appears in Link-in-Bio page'`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."custom_slug" IS 'Custom short URL slug (e.g., "my-link" for link.co/my-link)'`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_links"."product_id" IS 'Single product ID (NULL for multi-product links)'`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "tracking_link_products"."display_order" IS 'Order in which products appear on landing page (0-indexed)'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."product_review_status_enum_old" AS ENUM('PENDING_REVIEW', 'APPROVED', 'NEEDS_REVISION', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "review_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "review_status" TYPE "public"."product_review_status_enum_old" USING "review_status"::"text"::"public"."product_review_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "review_status" SET DEFAULT 'PENDING_REVIEW'`);
        await queryRunner.query(`DROP TYPE "public"."products_review_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."product_review_status_enum_old" RENAME TO "product_review_status_enum"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "product_url"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "product_url" character varying(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image_urls"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image_urls" text array DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "oauth_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "oauth_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "oauth_provider"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "oauth_provider" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."influencers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "status" character varying(20) DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_conversions" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_clicks" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_earnings" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_earnings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_sales" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "total_sales" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "rating" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "rating" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "niche"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "niche" character varying(100) array`);
        await queryRunner.query(`ALTER TABLE "influencers" ALTER COLUMN "follower_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_twitter"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_twitter" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_youtube"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_youtube" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_tiktok"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_tiktok" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "social_instagram"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "social_instagram" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "avatar_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "influencers" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD "display_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."brands_status_enum"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "status" character varying(20) DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "integration_type"`);
        await queryRunner.query(`DROP TYPE "public"."brands_integration_type_enum"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "integration_type" character varying(20) DEFAULT 'PIXEL'`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "UQ_2a36492bc579b1fe3895f806b90"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "pixel_id"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "pixel_id" character varying(32) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "brands_pixel_id_key" UNIQUE ("pixel_id")`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "UQ_86d76ffb685a202049e6e43d5f0"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "api_key"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "api_key" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "brands_api_key_key" UNIQUE ("api_key")`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "default_commission_rate" SET DEFAULT 0.1000`);
        await queryRunner.query(`ALTER TABLE "brands" ALTER COLUMN "default_commission_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "logo_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "website" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "display_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "company_name" character varying(255) NOT NULL`);
        await queryRunner.query(`COMMENT ON TABLE "campaign_invitations" IS 'Tracks invitations for SPECIFIC campaigns'`);
        await queryRunner.query(`COMMENT ON TABLE "tracking_link_products" IS 'Junction table for multi-product tracking links (2-10 products per link)'`);
        await queryRunner.query(`ALTER TABLE "campaign_invitations" ADD CONSTRAINT "UQ_campaign_invitations_campaign_influencer" UNIQUE ("campaign_id", "influencer_id")`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "UQ_conversions_brand_order" UNIQUE ("brand_id", "order_id")`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ADD CONSTRAINT "UQ_tracking_links_influencer_product" UNIQUE ("influencer_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "tracking_link_products" ADD CONSTRAINT "UQ_tracking_link_products_link_product" UNIQUE ("tracking_link_id", "product_id")`);
        await queryRunner.query(`ALTER TABLE "social_accounts" ADD CONSTRAINT "UQ_social_accounts_platform_user" UNIQUE ("platform", "platform_user_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['BRAND'::character varying, 'INFLUENCER'::character varying, 'ADMIN'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'DELETED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD CONSTRAINT "influencers_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'SUSPENDED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "brands_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'SUSPENDED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "brands_integration_type_check" CHECK (((integration_type)::text = ANY ((ARRAY['PIXEL'::character varying, 'WEBHOOK'::character varying, 'API'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "IDX_campaign_invitations_pending" ON "campaign_invitations" ("influencer_id", "status") WHERE (status = 'PENDING'::campaign_invitations_status_enum)`);
        await queryRunner.query(`CREATE INDEX "IDX_campaign_invitations_status" ON "campaign_invitations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaign_invitations_influencer" ON "campaign_invitations" ("influencer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaign_invitations_campaign" ON "campaign_invitations" ("campaign_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaigns_campaign_type" ON "campaigns" ("campaign_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaigns_end_date" ON "campaigns" ("end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaigns_start_date" ON "campaigns" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaigns_status" ON "campaigns" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaigns_brand_id" ON "campaigns" ("brand_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_is_read" ON "messages" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_created_at" ON "messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_brand_influencer" ON "messages" ("brand_id", "influencer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_created_at" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_is_read" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user" ON "notifications" ("user_id", "user_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_influencer_status" ON "payouts" ("influencer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_created_at" ON "payouts" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_status" ON "payouts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_influencer_id" ON "payouts" ("influencer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_clicks_product" ON "clicks" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clicks_ip" ON "clicks" ("ip_address", "clicked_at") `);
        await queryRunner.query(`CREATE INDEX "idx_clicks_clicked_at" ON "clicks" ("clicked_at") `);
        await queryRunner.query(`CREATE INDEX "idx_clicks_tracking_link" ON "clicks" ("tracking_link_id") `);
        await queryRunner.query(`CREATE INDEX "idx_conversions_status" ON "conversions" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_conversions_order_id" ON "conversions" ("brand_id", "order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_conversions_brand" ON "conversions" ("brand_id", "converted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_conversions_influencer" ON "conversions" ("influencer_id", "converted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_conversions_tracking_link" ON "conversions" ("tracking_link_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tracking_links_bio_links" ON "tracking_links" ("influencer_id", "is_bio_link") WHERE (is_bio_link = true)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_tracking_links_custom_slug" ON "tracking_links" ("custom_slug") WHERE (custom_slug IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_tracking_links_product" ON "tracking_links" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tracking_links_influencer" ON "tracking_links" ("influencer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tracking_links_code" ON "tracking_links" ("unique_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_tracking_link_products_product" ON "tracking_link_products" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tracking_link_products_link" ON "tracking_link_products" ("tracking_link_id", "display_order") `);
        await queryRunner.query(`CREATE INDEX "idx_products_review_status" ON "products" ("review_status") `);
        await queryRunner.query(`CREATE INDEX "idx_products_status" ON "products" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_products_category" ON "products" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_products_brand_id" ON "products" ("brand_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_oauth" ON "users" ("oauth_provider", "oauth_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_influencers_rating" ON "influencers" ("rating") `);
        await queryRunner.query(`CREATE INDEX "idx_influencers_niche" ON "influencers" ("niche") `);
        await queryRunner.query(`CREATE INDEX "idx_influencers_user_id" ON "influencers" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_accounts_platform" ON "social_accounts" ("platform") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_accounts_influencer" ON "social_accounts" ("influencer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_accounts_verified" ON "social_accounts" ("is_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_insights_type" ON "social_audience_insights" ("insight_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_insights_account" ON "social_audience_insights" ("social_account_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_metrics_synced" ON "social_metrics" ("synced_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_social_metrics_account" ON "social_metrics" ("social_account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_brands_api_key" ON "brands" ("api_key") `);
        await queryRunner.query(`CREATE INDEX "idx_brands_user_id" ON "brands" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "brand_integrations" ADD CONSTRAINT "FK_brand_integrations_brand" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_influencer" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_brand" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD CONSTRAINT "FK_1bfb3f36a926c9160ba5f96f249" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clicks" ADD CONSTRAINT "FK_b73adffd7ba59a8352387739b84" FOREIGN KEY ("tracking_link_id") REFERENCES "tracking_links"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_f26c816a183ac87bcca7810a464" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_ad3c2a862c329d544f652f7b83c" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_2b3de6b04e1a38f83e1e85c14be" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_35ca8b0cc9cd29f1ec4c404eb95" FOREIGN KEY ("tracking_link_id") REFERENCES "tracking_links"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ADD CONSTRAINT "FK_b3409d200515fd2deece569a82f" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking_links" ADD CONSTRAINT "FK_472c744e97dbcc4bab5ca63af01" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "influencers" ADD CONSTRAINT "fk_influencers_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_accounts" ADD CONSTRAINT "FK_social_accounts_influencer" FOREIGN KEY ("influencer_id") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_audience_insights" ADD CONSTRAINT "FK_social_insights_account" FOREIGN KEY ("social_account_id") REFERENCES "social_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_metrics" ADD CONSTRAINT "FK_social_metrics_account" FOREIGN KEY ("social_account_id") REFERENCES "social_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "fk_brands_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
